import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { BeamsBackground } from "@/components/ui/beams-background";
import { FloatingHeader } from "@/components/ui/floating-header";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <BeamsBackground className="fixed inset-0 -z-10" />
        <div className="relative z-10 min-h-screen flex flex-col">
          <div className="px-4 pt-5">
            <FloatingHeader />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
